-- 책 정보를 저장하는 테이블 생성하기
CREATE TABLE SAMPLE_BOOKS (
    BOOK_NO              NUMBER(6,0) PRIMARY KEY,
    BOOK_TITLE           VARCHAR2(500) NOT NULL,
    BOOK_WRITER          VARCHAR2(200) NOT NULL,
    BOOK_GENRE           VARCHAR2(200) NOT NULL,
    BOOK_PUBLISHER       VARCHAR2(200) NOT NULL,
    BOOK_PRICE           NUMBER(7,0) DEFAULT 0,
    BOOK_DISCOUNT_PRICE  NUMBER(7,0) NOT NULL,
    BOOK_REGISTERED_DATE DATE
);

-- 일련번호를 발행하는 시퀀스 생성하기
CREATE SEQUENCE SAMPLE_BOOK_SEQ START WITH 100000;

-- 고객 정보를 저장하는 테이블 생성하기
CREATE TABLE SAMPLE_BOOK_USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USER_PASSWORD VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(256) NOT NULL,
    USER_POINT NUMBER(10, 0),
    USER_REGISTERED_DATE DATE
);

CREATE TABLE SAMPLE_BOOK_ORDERS (
    ORDER_NO NUMBER(6,0) PRIMARY KEY,                               -- 주문번호
    USER_ID VARCHAR2(50) REFERENCES SAMPLE_BOOK_USERS (USER_ID),    -- 주문자 아이디
    BOOK_NO NUMBER(6,0) REFERENCES SAMPLE_BOOKS(BOOK_NO),           -- 주문도서 번호
    ORDER_PRICE NUMBER(7,0),                                        -- 구매가격
    ORDER_AMOUNT NUMBER(3,0),                                       -- 구매수량
    ORDER_REGISTERED_DATE DATE                                      -- 주문날짜
);

-- 주문번호 발생기 생성
CREATE SEQUENCE SAMPLE_ORDER_SEQ START WITH 500000;

-- 사용자 등록
INSERT INTO SAMPLE_BOOK_USERS
(USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL, USER_POINT, USER_REGISTERED_DATE)
VALUES
('hong', 'zxcv1234', '홍길동', 'hong@gmail.com', 1000, SYSDATE);

-- 주문 등록
INSERT INTO SAMPLE_BOOK_ORDERS
(ORDER_NO, USER_ID, BOOK_NO, ORDER_PRICE, ORDER_AMOUNT, ORDER_REGISTERED_DATE)
VALUES
(SAMPLE_ORDER_SEQ.NEXTVAL, 'hong', 100008, 16200, 2, SYSDATE);

-- 책 정보 등록하기
INSERT INTO SAMPLE_BOOKS
(BOOK_NO, BOOK_TITLE, BOOK_WRITER, BOOK_GENRE, BOOK_PUBLISHER, BOOK_PRICE, BOOK_DISCOUNT_PRICE, BOOK_REGISTERED_DATE)
VALUES
(SAMPLE_BOOK_SEQ.NEXTVAL, '자바의 정석', '남궁성', 'IT', '도우출판사', '30000', '27000', SYSDATE);