SELECT *
FROM SAMPLE_BOOK_USERS;

-- 트랜잭션 처리
INSERT INTO SAMPLE_BOOK_USERS                                   -- 트랜잭션 시작
(USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL)
VALUES
('hong5678', 'zxcv1234', '홍홍홍홍', 'hong5678@gmail.com');

UPDATE SAMPLE_BOOK_USERS
SET USER_POINT = 1000
WHERE USER_ID = 'hong5678';

SAVEPOINT ADD_NEW_USER;                                         -- 저장지점 지정

INSERT INTO SAMPLE_BOOK_ORDERS (ORDER_NO, USER_ID, BOOK_NO, ORDER_PRICE, ORDER_AMOUNT)
VALUES (SAMPLE_ORDER_SEQ.NEXTVAL, 'hong', 100009, 16200, 2);

UPDATE SAMPLE_BOOK_USERS
SET USER_POINT = USER_POINT + TRUNC(22500*3*0.03)
WHERE USER_ID = 'hong5678';

COMMIT;             -- 현재 트랜잭션의 변경내용을 저장, 현재 트랜잭션 종료, 새 트랜잭션 시작

-- DML1 작업
-- DML2 작업
-- DML3 작업

ROLLBACK;           -- 새로 시작된 트랜잭션의 변경내용(DML1~3)을 버림, 트랜잭션 종료, 새 트랜잭션 시작

SELECT *
FROM SAMPLE_BOOK_USERS;

SELECT *
FROM SAMPLE_BOOK_ORDERS;

ROLLBACK TO SAVEPOINT ADD_NEW_USER;

SELECT * FROM SAMPLE_BOOK_ORDERS;
SELECT * FROM SAMPLE_BOOK_USERS;

SELECT ROWID, USER_ID, USER_EMAIL
FROM SAMPLE_BOOK_USERS;

-- 북스토어 문의/답변 게시판
-- 번호, 제목, 작성자, 내용, 조회수, 작성일, 상태(답변완료여부), 질문유형
-- number, varchar2, varchar2, varchar2, number, date, char, varchar2
CREATE TABLE SAMPLE_BOOK_QUESTIONS (
    QUESTION_NO              NUMBER(7, 0) PRIMARY KEY,
    QUESTION_TITLE           VARCHAR2(500) NOT NULL,
    USER_ID                  VARCHAR2(50) REFERENCES SAMPLE_BOOK_USERS (USER_ID),
    QUESTION_CONTENT         VARCHAR2(4000) NOT NULL,
    QUESTION_VIEW_COUNT      NUMBER(7, 0) DEFAULT 0,
    QUESTION_REGISTERED_DATE DATE DEFAULT SYSDATE,
    QUESTION_STATUS          CHAR(1) DEFAULT 'N',
    QUESTION_TYPE            VARCHAR2(200) NOT NULL
);

-- 북스토어 답변 게시판
-- 번호, 내용, 작성일, 문의글 번호
-- NUMBER, VARCHAR2, DATE, NUMBER
CREATE TABLE SAMPLE_BOOKSTORE_ANSWERS (
    ANSWER_NO              NUMBER(7, 0) PRIMARY KEY,
    ANSWER_CONTENT         VARCHAR2(4000) NOT NULL,
    ANSWER_REGISTERED_DATE DATE DEFAULT SYSDATE,
    QUESTION_NO            NUMBER(7, 0) REFERENCES SAMPLE_BOOK_QUESTIONS (QUESTION_NO)
);

-- 테이블 이름 변경하기
RENAME SAMPLE_BOOKSTORE_ANSWERS TO SAMPLE_BOOK_ANSWERS;

-- 문의/답변 게시판을 일련번호 생성기 만들기
CREATE SEQUENCE SAMPLE_QUESTION_SEQ START WITH 1000000 NOCACHE;
CREATE SEQUENCE SAMPLE_ANSWER_SEQ START WITH 1000000 NOCACHE;