CREATE TABLE SAMPLE_SCHOOL_DEPARTMENTS (
DEPARTMENT_NO NUMBER(7,0) PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(4000) NOT NULL
);

CREATE SEQUENCE SAMPLE_SCHOOL_DEPARTMENTS_SEQ START WITH 100 NOCACHE;

INSERT INTO SAMPLE_SCHOOL_DEPARTMENTS
(DEPARTMENT_NO, DEPARTMENT_NAME)
VALUES
(SAMPLE_SCHOOL_DEPARTMENTS_SEQ.NEXTVAL, '경영학과');

INSERT INTO SAMPLE_SCHOOL_DEPARTMENTS
(DEPARTMENT_NO, DEPARTMENT_NAME)
VALUES
(SAMPLE_SCHOOL_DEPARTMENTS_SEQ.NEXTVAL, '컴퓨터공학과');

INSERT INTO SAMPLE_SCHOOL_DEPARTMENTS
(DEPARTMENT_NO, DEPARTMENT_NAME)
VALUES
(SAMPLE_SCHOOL_DEPARTMENTS_SEQ.NEXTVAL, '의예학과');

INSERT INTO SAMPLE_SCHOOL_DEPARTMENTS
(DEPARTMENT_NO, DEPARTMENT_NAME)
VALUES
(SAMPLE_SCHOOL_DEPARTMENTS_SEQ.NEXTVAL, '호텔경영학과');

INSERT INTO SAMPLE_SCHOOL_DEPARTMENTS
(DEPARTMENT_NO, DEPARTMENT_NAME)
VALUES
(SAMPLE_SCHOOL_DEPARTMENTS_SEQ.NEXTVAL, '영어학과');

CREATE TABLE SAMPLE_SCHOOL_PROFESSORS (
PROFESSOR_NO NUMBER(7,0) PRIMARY KEY,
PROFESSOR_NAME VARCHAR2(4000) NOT NULL,
PROFESSOR_POSITION VARCHAR2(4000) NOT NULL,
DEPARTMENT_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_DEPARTMENTS (DEPARTMENT_NO),
PROFESSOR_REGISTERED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SAMPLE_SCHOOL_PROFESSORS_SEQ START WITH 300 NOCACHE;

INSERT INTO SAMPLE_SCHOOL_PROFESSORS
(PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_POSITION, DEPARTMENT_NO, PROFESSOR_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_PROFESSORS_SEQ.NEXTVAL, '김교수', '학과장', 100, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_PROFESSORS
(PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_POSITION, DEPARTMENT_NO, PROFESSOR_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_PROFESSORS_SEQ.NEXTVAL, '박교수', '정교수', 100, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_PROFESSORS
(PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_POSITION, DEPARTMENT_NO, PROFESSOR_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_PROFESSORS_SEQ.NEXTVAL, '이교수', '정교수', 101, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_PROFESSORS
(PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_POSITION, DEPARTMENT_NO, PROFESSOR_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_PROFESSORS_SEQ.NEXTVAL, '신교수', '학과장', 103, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_PROFESSORS
(PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_POSITION, DEPARTMENT_NO, PROFESSOR_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_PROFESSORS_SEQ.NEXTVAL, '곽교수', '정교수', 102, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_PROFESSORS
(PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_POSITION, DEPARTMENT_NO, PROFESSOR_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_PROFESSORS_SEQ.NEXTVAL, '강교수', '정교수', 101, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_PROFESSORS
(PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_POSITION, DEPARTMENT_NO, PROFESSOR_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_PROFESSORS_SEQ.NEXTVAL, '윤교수', '정교수', 104, SYSDATE);

CREATE TABLE SAMPLE_SCHOOL_STUDENTS (
STUDENT_NO NUMBER(7,0) PRIMARY KEY,
STUDENT_NAME VARCHAR2(4000) NOT NULL,
STUDENT_GRADE NUMBER(7,0) NOT NULL,
DEPARTMENT_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_DEPARTMENTS (DEPARTMENT_NO),
STUDENT_REGISTERED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SAMPLE_SCHOOL_STUDENTS_SEQ START WITH 500 NOCACHE;

INSERT INTO SAMPLE_SCHOOL_STUDENTS
(STUDENT_NO, STUDENT_NAME, STUDENT_GRADE, DEPARTMENT_NO, STUDENT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_STUDENTS_SEQ.NEXTVAL, '홍길동', 2, 100, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_STUDENTS
(STUDENT_NO, STUDENT_NAME, STUDENT_GRADE, DEPARTMENT_NO, STUDENT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_STUDENTS_SEQ.NEXTVAL, '김민수', 3, 100, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_STUDENTS
(STUDENT_NO, STUDENT_NAME, STUDENT_GRADE, DEPARTMENT_NO, STUDENT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_STUDENTS_SEQ.NEXTVAL, '이순신', 4, 102, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_STUDENTS
(STUDENT_NO, STUDENT_NAME, STUDENT_GRADE, DEPARTMENT_NO, STUDENT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_STUDENTS_SEQ.NEXTVAL, '임꺽정', 3, 101, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_STUDENTS
(STUDENT_NO, STUDENT_NAME, STUDENT_GRADE, DEPARTMENT_NO, STUDENT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_STUDENTS_SEQ.NEXTVAL, '일지매', 1, 101, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_STUDENTS
(STUDENT_NO, STUDENT_NAME, STUDENT_GRADE, DEPARTMENT_NO, STUDENT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_STUDENTS_SEQ.NEXTVAL, '척준경', 4, 104, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_STUDENTS
(STUDENT_NO, STUDENT_NAME, STUDENT_GRADE, DEPARTMENT_NO, STUDENT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_STUDENTS_SEQ.NEXTVAL, '원균', 3, 103, SYSDATE);

CREATE TABLE SAMPLE_SCHOOL_SUBJECTS (
SUBJECT_NO NUMBER(7,0) PRIMARY KEY,
SUBJECT_NAME VARCHAR2(4000) NOT NULL,
DEPARTMENT_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_DEPARTMENTS (DEPARTMENT_NO),
SUBJECT_REGISTERED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SAMPLE_SCHOOL_SUBJECTS_SEQ START WITH 700 NOCACHE;

INSERT INTO SAMPLE_SCHOOL_SUBJECTS
(SUBJECT_NO, SUBJECT_NAME, DEPARTMENT_NO, SUBJECT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_SUBJECTS_SEQ.NEXTVAL, '경영학원론', 100, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_SUBJECTS
(SUBJECT_NO, SUBJECT_NAME, DEPARTMENT_NO, SUBJECT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_SUBJECTS_SEQ.NEXTVAL, '컴퓨터와 자료구조', 101, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_SUBJECTS
(SUBJECT_NO, SUBJECT_NAME, DEPARTMENT_NO, SUBJECT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_SUBJECTS_SEQ.NEXTVAL, '기초의학', 102, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_SUBJECTS
(SUBJECT_NO, SUBJECT_NAME, DEPARTMENT_NO, SUBJECT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_SUBJECTS_SEQ.NEXTVAL, '주장관리론', 103, SYSDATE);

INSERT INTO SAMPLE_SCHOOL_SUBJECTS
(SUBJECT_NO, SUBJECT_NAME, DEPARTMENT_NO, SUBJECT_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_SUBJECTS_SEQ.NEXTVAL, '심화영어', 104, SYSDATE);

CREATE TABLE SAMPLE_SCHOOL_COURSES (
COURSE_NO NUMBER(7,0) PRIMARY KEY,
COURSE_NAME VARCHAR2(50) NOT NULL,
DEPARTMENT_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_DEPARTMENTS (DEPARTMENT_NO),
SUBJECT_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_SUBJECTS (SUBJECT_NO),
PROFESSOR_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_PROFESSORS (PROFESSOR_NO),
COURSE_QUOTA NUMBER(7,0) NOT NULL,
COURSE_DEADLINE CHAR(1) CHECK(COURSE_DEADLINE IN ('Y', 'N')),
COURSE_REGISTERED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SAMPLE_SCHOOL_COURSES_SEQ START WITH 900 NOCACHE;

INSERT INTO SAMPLE_SCHOOL_COURSES
(COURSE_NO, COURSE_NAME, DEPARTMENT_NO, SUBJECT_NO, PROFESSOR_NO, COURSE_QUOTA, COURSE_DEADLINE, COURSE_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_COURSES_SEQ.NEXTVAL, '과정001', 100, 705, 308, 20, 'N', SYSDATE);

INSERT INTO SAMPLE_SCHOOL_COURSES
(COURSE_NO, COURSE_NAME, DEPARTMENT_NO, SUBJECT_NO, PROFESSOR_NO, COURSE_QUOTA, COURSE_DEADLINE, COURSE_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_COURSES_SEQ.NEXTVAL, '과정002', 101, 706, 310, 25, 'N', SYSDATE);

INSERT INTO SAMPLE_SCHOOL_COURSES
(COURSE_NO, COURSE_NAME, DEPARTMENT_NO, SUBJECT_NO, PROFESSOR_NO, COURSE_QUOTA, COURSE_DEADLINE, COURSE_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_COURSES_SEQ.NEXTVAL, '과정003', 102, 707, 312, 15, 'N', SYSDATE);

INSERT INTO SAMPLE_SCHOOL_COURSES
(COURSE_NO, COURSE_NAME, DEPARTMENT_NO, SUBJECT_NO, PROFESSOR_NO, COURSE_QUOTA, COURSE_DEADLINE, COURSE_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_COURSES_SEQ.NEXTVAL, '과정004', 103, 708, 311, 20, 'N', SYSDATE);

INSERT INTO SAMPLE_SCHOOL_COURSES
(COURSE_NO, COURSE_NAME, DEPARTMENT_NO, SUBJECT_NO, PROFESSOR_NO, COURSE_QUOTA, COURSE_DEADLINE, COURSE_REGISTERED_DATE)
VALUES
(SAMPLE_SCHOOL_COURSES_SEQ.NEXTVAL, '과정005', 104, 709, 314, 20, 'N', SYSDATE);

CREATE TABLE SAMPLE_SCHOOL_REGISTRATIONS (
REGISTRATION_NO NUMBER(7,0) PRIMARY KEY,
COURSE_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_COURSES (COURSE_NO),
STUDENT_NO NUMBER(7,0) REFERENCES SAMPLE_SCHOOL_STUDENTS (STUDENT_NO),
REGISTRATION_CANCEL CHAR(1) CHECK(REGISTRATION_CANCEL IN ('Y', 'N')),
REGISTRATION_COMPLETION CHAR(1) CHECK(REGISTRATION_COMPLETION IN ('Y', 'N')),
REGISTRATION_SCORE NUMBER(10,0) NOT NULL,
REGISTRATION_REGISTERED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SAMPLE_SCHOOL_REG_SEQ START WITH 1100 NOCACHE;

COMMIT;

COMMIT;