-- 1.  시스템의 현재 날짜와 시간 조회하기 (dual 사용)
SELECT SYSDATE
FROM DUAL;
-- 2.  급여를 5000달러 이상받고, 2005년에 입사한 직원의 아이디, 이름, 급여, 입사일을 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2005'
AND SALARY >= 5000;
-- 3.  이름에 e나 E가 포함된 직원 중에서 급여를 10000달러 이상 받는 직원의 아이디, 이름, 급여를 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 10000
AND FIRST_NAME LIKE '%E%'
OR FIRST_NAME LIKE '%e%';
-- 4.  입사년도와 상관없이 4월에 입사한 직원들의 아이디, 이름, 입사일을 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'MM') = '04'
-- 5.  2006년 상반기(1/1 ~ 6/30)에 입사한 직원들의 아이디, 이름, 입사일 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE >= '2006/01/01'
AND HIRE_DATE <= '2006/06/30'
ORDER BY HIRE_DATE ASC;
-- 6.  50번 부서에 소속된 직원들의 급여를 13%인상시키려고 한다.
--     직원아이디, 이름, 현재 급여, 인상된 급여를 조회하기
--     인상된 급여는 소숫점 이하는 버린다.
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, TRUNC(SALARY * 1.13) AS INCREASED_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;
-- 7.  50번 부서에 소속된 직원들의 급여를 조회하려고 한다.
--     직원 아이디, 이름, 급여 그리고, 급여 1000달러당 *를 하나씩 표시하라.
--     120 Matthew 8000 ********
--     122 Shanta  6500 ******
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, LPAD('*', TRUNC(SALARY / 1000), '*')
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;
-- 8.  관리자가 지정되어 있지 않는 부서의 
--     부서아이디, 부서명, 위치아이디, 도시명, 주소를 조회하기
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.LOCATION_ID, B.CITY, B.STREET_ADDRESS
FROM DEPARTMENTS A, LOCATIONS B
WHERE A.MANAGER_ID IS NULL
AND A.LOCATION_ID = B.LOCATION_ID
ORDER BY DEPARTMENT_ID ASC;
-- 9.  90번 부서에 소속된 직원의 직원아이디, 이름, 직종, 급여를 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;
-- 10. 100번 직원이 부서관리자로 지정된 부서에 소속된 직원의 직원아이디, 이름, 직종, 급여를 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.JOB_ID, A.SALARY
FROM EMPLOYEES A, DEPARTMENTS B
WHERE B.MANAGER_ID = 100
and A.DEPARTMENT_ID = B.DEPARTMENT_ID;
-- 11. 10, 20, 30번 부서에 소속된 직원들의 직원아이디, 이름, 급여, 급여등급을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY, B.GRA
FROM EMPLOYEES A, JOB_GRADES B
WHERE A.DEPARTMENT_ID IN (10, 20, 30)
AND A.SALARY >= B.LOWEST_SAL
AND A.SALARY <= B.HIGHEST_SAL
ORDER BY EMPLOYEE_ID ASC;
-- 12. 직원들의 직종정보를 참고했을 때 자신이 종사하고 있는 직종의 최저급여를 받고 있는
--     직원의 아이디, 이름, 급여, 직종아이디, 직종최저급여를 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY, B.JOB_ID, B.MIN_SALARY
FROM EMPLOYEES A, JOBS B
WHERE A.JOB_ID = B.JOB_ID
AND A.SALARY = B.MIN_SALARY;
-- 13. 커미션을 받는 직원들의 직원아이디, 이름, 커미션, 급여, 직종아이디, 직종제목, 급여, 소속부서 아이디, 부서명을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.COMMISSION_PCT, A.SALARY, B.JOB_ID, B.JOB_TITLE, C.DEPARTMENT_ID, C.DEPARTMENT_NAME
FROM EMPLOYEES A, JOBS B, DEPARTMENTS C
WHERE A.COMMISSION_PCT IS NOT NULL
AND A.JOB_ID = B.JOB_ID
AND A.DEPARTMENT_ID = C.DEPARTMENT_ID
ORDER BY A.EMPLOYEE_ID ASC;
-- 14. 'Canada'에서 근무하고 있는 직원의 아이디, 이름, 소속부서 아이디, 소속부서명, 위치 아이디, 도시명, 주소를 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAME, C.LOCATION_ID, C.CITY, C.STREET_ADDRESS
FROM EMPLOYEES A, DEPARTMENTS B, LOCATIONS C, COUNTRIES D
WHERE D.COUNTRY_NAME = 'Canada'
AND A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND B.LOCATION_ID = C.LOCATION_ID
AND C.COUNTRY_ID = D.COUNTRY_ID
ORDER BY A.EMPLOYEE_ID ASC;
-- 15. 모든 직원의 직원아이디, 이름, 직종아이디, 직종제목, 급여, 급여등급, 소속부서 아이디, 소속부서명, 도시명을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, B.JOB_ID, B.JOB_TITLE, A.SALARY, D.GRA, C.DEPARTMENT_ID, C.DEPARTMENT_NAME, E.CITY
FROM EMPLOYEES A, JOBS B, DEPARTMENTS C, JOB_GRADES D, LOCATIONS E
WHERE A.DEPARTMENT_ID = C.DEPARTMENT_ID
AND A.JOB_ID = B.JOB_ID
AND C.LOCATION_ID = E.LOCATION_ID
AND A.SALARY >= D.LOWEST_SAL
AND A.SALARY <= D.HIGHEST_SAL
ORDER BY A.EMPLOYEE_ID ASC;
-- 16. 급여를 5000달러 이하로 받는 직원들의 아이디, 이름, 직종, 소속부서 아이디, 소속부서명, 소속부서 관리자 직원아이디, 
--     소속부서 관리자 직원이름을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.JOB_ID, B.DEPARTMENT_ID, B.DEPARTMENT_NAME, B.MANAGER_ID
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.SALARY <= 5000
AND A.EMPLOYEE_ID = B.MANAGER_ID
ORDER BY A.EMPLOYEE_ID ASC;
-- 17. 'Asia'지역에 소재지를 두고 있는 부서의 아이디, 부서명, 부서관리자 이름을 조회하기
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, A.MANAGER_ID
FROM DEPARTMENTS A, LOCATIONS B, COUNTRIES C, REGIONS D
WHERE D.REGION_NAME = 'Asia'
AND A.LOCATION_ID = B.LOCATION_ID
AND B.COUNTRY_ID = C.COUNTRY_ID
AND C.REGION_ID = D.REGION_ID;
-- 18. 101번 직원이 근무했던 부서에서 근무중이 직원의 아이디, 이름, 부서아이디, 부서명을 조회하기
SELECT DISTINCT A.EMPLOYEE_ID, A.FIRST_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B, JOB_HISTORY C
WHERE C.EMPLOYEE_ID = 101
AND B.DEPARTMENT_ID = C.DEPARTMENT_ID
AND A.DEPARTMENT_ID = B.DEPARTMENT_ID;
-- 19. 직원중에서 자신이 종사하고 있는 직종의 최고급여 50%이상을 급여로 받고 있는 
--     직원의 아이디, 이름, 급여, 직종아이디, 직종 최고급여를 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY, B.JOB_ID, B.MAX_SALARY
FROM EMPLOYEES A, JOBS B
WHERE A.SALARY >= B.MAX_SALARY / 2
AND A.JOB_ID = B.JOB_ID;
-- 20. 미국(US)에 위치하고 있는 부서의 아이디, 이름, 위치번호, 도시명, 주소를 조회하기 
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.LOCATION_ID, B.CITY, B.STREET_ADDRESS
FROM DEPARTMENTS A, LOCATIONS B
WHERE B.COUNTRY_ID = 'US'
AND A.LOCATION_ID = B.LOCATION_ID
ORDER BY A.DEPARTMENT_ID ASC;