-- 부서 아이디, 부서명, 부서에 소속된 사원수, 부서의 총 연봉 조회하기
SELECT DEPARTMENT_ID,
       DEPARTMENT_NAME,
       GET_EMP_COUNT(DEPARTMENT_ID),
       GET_DEPT_TOTAL_SALARY(DEPARTMENT_ID)
FROM DEPARTMENTS;


-- 트리거 생성하기
-- SAMPLE_BOOK_LIKES에 INSERT 작업이 실행될 때마다 자동으로 SAMPLE_BOOKS의 BOOK_LIKES 컬럼의 값을 1 증가시킨다.
CREATE OR REPLACE TRIGGER INCREASE_BOOK_LIKES_TRIGGER
    AFTER
    INSERT ON SAMPLE_BOOK_LIKES
    FOR EACH ROW
    
    BEGIN
    
    UPDATE SAMPLE_BOOKS
    SET
        BOOK_LIKES = BOOK_LIKES + 1
    WHERE
        BOOK_NO = :NEW.BOOK_NO;
    
    END;