CREATE SEQUENCE SCHOOL_DEPT_SEQ START WITH 10 INCREMENT BY 10 NOCACHE;

CREATE SEQUENCE SCHOOL_PROF_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SCHOOL_STUDENT_SEQ START WITH 5000 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SCHOOL_SUBJECT_SEQ START WITH 100 INCREMENT BY 10 NOCACHE;

CREATE SEQUENCE SCHOOL_COURSE_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SCHOOL_COURSE_REG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE VIEW SCHOOL_COURSES_VIEW
AS
    SELECT A.COURSE_NO, 
           A.COURSE_NAME, 
           A.COURSE_QUOTA, 
           A.COURSE_REG_CNT, 
           A.COURSE_CLOSED, 
           B.SUBJECT_NO, 
           B.SUBJECT_NAME, 
           C.PROF_NO,
           C.PROF_NAME, 
           D.DEPT_NO, 
           D.DEPT_NAME, 
           A.COURSE_CREATE_DATE
    FROM SCHOOL_COURSES A, SCHOOL_SUBJECTS B, SCHOOL_PROFESSORS C, SCHOOL_DEPT D
    WHERE A.SUBJECT_NO = B.SUBJECT_NO
    AND A.PROF_NO = C.PROF_NO
    AND B.DEPT_NO = D.DEPT_NO;
    
    -- 개설과정 상세보기
    SELECT *
    FROM SCHOOL_COURSES_VIEW
    WHERE COURSE_NO = ?;
    
    -- 00학과에서 개설한 과정 보기
    SELECT *
    FROM SCHOOL_COURSES_VIEW
    WHERE DEPT_NAME = ?;
    
    -- 00교수가 개설한 과정 보기
    SELECT *
    FROM SCHOOL_COURSES_VIEW
    WHERE PROF_NAME = ?;
    
    -- 마감되지 않은 과정 보기
    SELECT *
    FROM SCHOOL_COURSES_VIEW
    WHERE COURSE_CLOSED = 'N';